### ISSUE TITLE
SME Review Checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-jms-intro#49]
SME Review:

Review of the guide by a Subject Matter Expert (SME) for technical accuracy and content.

- [x] Ensure technical accuracy for code
- [x] Ensure technical accuracy for guide
- [x] Ensure technical accuracy for overall content

**Comment by sakerl** [comment]
I think everything is technically correct, but attached are some thoughts/questions/suggestions:

## What you’ll learn

Would
> "You will learn how to communicate Java services..."

be better as "You will learn how to communicate *between* Java services..."

---

In the sentence:
> "You’ll create the system and inventory microservices using Java Message System."

The term "Java Message System" hasn't been used before this. Was this intended to be "Java Message Service", that is, the previous name for Jakarta Messaging?

---

## Creating the consumer in the inventory microservice

The InventoryQueueListener.java uses the annotation
> @MessageDriven(mappedName = "jms/InventoryQueue")

The mappedName property is provider specific, so wouldn't be portable. This might not be an issue seeing as this is a specifically Liberty oriented guide, but and alternative would be to use the activationConfig property and use @ActivationConfigProperty annotations to define the DestinationType and DestinationLookup.

---

When the InventoryQueueListener.java file is first saved, and the application deployed, the Liberty server will log a warning like:

> [INFO] [INFO    ] CNTR0180I: The InventoryQueueListener message-driven bean in the guide-jms-intro-inventory.war module of the guide-jms-intro-inventory application is bound to the guide-jms-intro-inventory/InventoryQueueListener activation specification.
[INFO] [WARNING ] CNTR4015W: The message endpoint for the InventoryQueueListener message-driven bean cannot be activated because the guide-jms-intro-inventory/InventoryQueueListener activation specification is not available. The message endpoint will not receive messages until the activation specification becomes available.

because at this point no activationSpec has been defined. Would it be safer to note that this will happen so that someone following the guide doesn't worry that they've made a mistake somewhere?

---

In the server.xml file, you are defining a jmsQueueConnectionFactory. This is the old, JMS 1.1 domain-specific object. As of JMS 1.1 you can also instantiate a jmsConnectionFactory. While in this scenario there wouldn't be a functional difference, using a jmsConnectionFactory would allow the applications to be expanded or rewritten to use publish-subscribe messaging as well as point-to-point messaging from the same starting factory object, or the same Context/Connection instead of requiring different factories and different connections.

---

In inventory/server.xml There is a comment before the wasJmsEndpoint element:
> 

This is potentially a little confusing. The wasJmsEndpoint defines the endpoint that allows a client to connect to the messaging provider. It isn't specific to the Inventory queue, it's just that in this scenario the Inventory queue is the only queue defined.

---

The explanation
> The messaging feature enables the configuration of resource adapters to access messaging systems by using the Jakarta Messaging API. The messagingClient feature enables the application with access to the message queues that are hosted on Liberty through the Jakarta Messaging API. The messagingServer feature enables an embedded messaging server to listen the message queues.

could be a little more specific:
  The messagingServer feature enables a Liberty server to host an embedded messaging server to manage messaging destinations.
  The messagingClient feature enables applications to connect to a Liberty messaging server and access the messaging destinations hosted on that server through the Jakarta Messaging API.

(We are only using queues in this example, but Jakarta Messaging also includes publish/subscribe topics).

---

The queue on which the MDB is listening is defined in two different places; within the @MessageDriven annotation in the class itself, and also in the jmsActivationSpec element in the server.xml file. It technically should only need to be defined in one place, it's possible that defining the queue in both places might be confusing.

---

Another stylistic suggestion. The Queue used by the System application is configured to accept messages as reliablePersistent. Also, the messages are sent with a default time to live, which means that the messages will never expire. If the MDB were to be stopped for any reason, then these messages would build up on the queue. When the MDB was restarted it would then have to work through receiving and processing any messages that hadn't yet been received. If we assume that the purpose of the application is to monitor the current cpu load (as opposed to recording a complete timeline including values in the past) then this means the MDB will be processing messages unnecessarily. If the messages were given a time to live value so that they expired after a period of time, then in the case where the MDB was temporarily stopped, these messages could expire and wouldn't be processed (note, they would still persist on the queue until something was processing the queue and they could be identified as expired and then removed). On a similar note, persistent messages will survive a messaging engine restart, so currently if the server is restarted, any previously sent but unprocessed messages will remain on the queue and be processed after the restart. If the messages were sent as nonpersistent then they would be deleted if the messaging engine was restarted, so only new messages would be received by the MDB after that point.

---

## Using IBM MQ - Optional

Mac on Intel doesn't require building your own image, you can simply pull the developer MQ image from icr.io in the same way as for Linux.

---

Technically, once MQ and the MQ Resource Adapter are being used as the messaging provider, the previously defined messaging engine in the inventory/server.xml could be removed, as could the jmsQueueConnectionFactory definition in the same file as they are no longer being used.

**Comment by gkwan-ibm** [comment]
close
- updated by PR #50
